
#define SHIELDTOPY      144
#define PLAYERY         168

#define SAUCERSPEED     3
#define SHOTSPEED       5
#define PLAYERSPEED     0 

#define SAUCERTIMER     0x500 
#define SAUCERROW       16

#define ALIENSPEED      1 
#define ALIENSHOTSPEED  2

#define FLEETDELTAY     4

#define FLEETPOSSTART   88

#define DEMOSPEED       50


#define SOUND_UFO               1
#define SOUND_PLAYER_SHOT       2
#define SOUND_PLAYER_EXPLOSION  3
#define SOUND_ALIEN_EXPLOSION   4
#define SOUND_ALIEN_STEP1       5
#define SOUND_ALIEN_STEP2       6
#define SOUND_ALIEN_STEP3       7
#define SOUND_ALIEN_STEP4       8
#define SOUND_UFO_EXPLOSION     9
#define SOUND_EXTRA_LIFE        10

#define SOUND_SYS_OFF           0
#define SOUND_SYS_ZONX          1
#define SOUND_SYS_BEEPER        1
#define SOUND_SYS_SINCLAIR128K  2
#define SOUND_SYS_FULLERBOX     3
#define SOUND_SYS_TS2068        4


#define NUM_UNSIGNED 0x80
#define NUM_LEFTZERO 0x60
